version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flexliving-reviews-db
    environment:
      POSTGRES_DB: flexliving_reviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: flexliving-reviews-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/flexliving_reviews
      HOSTAWAY_ACCOUNT_ID: 61148
      HOSTAWAY_API_KEY: your_hostaway_api_key_here
      HOSTAWAY_BASE_URL: https://sandbox-api.hostaway.com
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
